name: tarea6
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  location: ^4.4.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/andy.jpg'
  adaptive_icon_background: 'assets/images/andy.jpg'

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/